### ISSUE TITLE
HTTP status 500 when running the code

### ISSUE THREAD

**Issue by thaingo** [pugnascotia/spring-react-boilerplate#1]
@RoryHunter 
Thank you for the nice work.

I encountered an issue. Executing mvn (or ./mvnw) went smoothly but when I visited http://localhost:8080, it gave me an error:
HTTP Status 500 - Request processing failed; nested exception is java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: No serializer found for class jdk.nashorn.internal.runtime.arrays.NoTypeArrayData and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) ) (through reference chain: jdk.nashorn.internal.scripts.JO4["proto"]->jdk.nashorn.internal.objects.NativeObject$Prototype["array"])

Could you please look into this?

Thank you.

**Comment by pugnascotia** [comment]
Strange, it works for me. What version of Java are you using? I have:

```
$ java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
```

**Comment by thaingo** [comment]
Thanks for the quick response. I have:

$ java -version
java version "1.8.0_11"
Java(TM) SE Runtime Environment (build 1.8.0_11-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.11-b03, mixed mode)

I would update Java to latest version and see if the issue is fixed.

**Comment by pugnascotia** [comment]
Yes, you need to have at least 1.8.0_65, as per `README.md`. Let me know if that fixes the issue.

**Comment by thaingo** [comment]
It works perfectly and thanks for your time.
Sorry for not reading the Readme carefully.

**Comment by pugnascotia** [comment]
No worries, let me know if you need help with anything else.
