### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Totollie** [pugnascotia/spring-react-boilerplate#3]
Hi, there is a chance I have missed the relevant information somewhere, but which pretence do you allow this code to be used under? It looks great as a way of using Spring Boot with React Router as there does not seem to be much information available on this.

Thank you.

**Comment by pugnascotia** [comment]
This repository was originally built alongside this blog:

http://www.blackpepper.co.uk/spring-react-redux-routing/

Do you have any specific questions on how to integrate Spring and react-router?

**Comment by pugnascotia** [comment]
I added a license file in commit 99f519f, specifying MIT.
