### ISSUE TITLE
Failed to render script template

### ISSUE THREAD

**Issue by datanguyen** [pugnascotia/spring-react-boilerplate#5]
Hi Rory,

When I first run applications I got the issue about the ENN=production webpack because I am a Window user. Then, I change these line of code in the package.json file as "SET NODE_ENV=development node foo.js", the application runs well.
However when I access the link localhost:8080, I got an issue as follow:

> HTTP Status 500 - Failed to render script template
> 
> **exception**
> javax.servlet.ServletException: Failed to render script template
> 
> org.springframework.web.servlet.view.script.ScriptTemplateView.renderMergedOutputModel(ScriptTemplateView.java:363)
>   org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303)
>   org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1243)
> 
> **root cause**:
>  org.springframework.scripting.support.StandardScriptEvalException: ReferenceError: "ReactDemo" is not defined in <eval>#1:6653<eval> at line number 26 at column number 57

**Comment by pugnascotia** [comment]
That's very strange - `ReactDemo` should be the first thing that `src/main/resources/static/app/bundle.js` defines. Can you check your copy of this file (it's generated by `npm run build`, which you've probably already seen) and make sure it starts with `var ReactDemo = ....`?

If I can get access to a Windows machines, I'll try and replicate the issue.

**Comment by pugnascotia** [comment]
You can now also run `npm run debug`, which will build a non-uglified bundle. Can you try that and see if it starts with `var ReactDemo =`?

**Comment by datanguyen** [comment]
Hi Rory,
I have been trying many ways with the npm but the bundle.js  was always not found.
There is not file bundle.js created in `src/main/resources/static/app/bundle.js`

**Comment by pugnascotia** [comment]
And is the bundle not generated if you execute `mvn compile` instead of `npm`?

**Comment by datanguyen** [comment]
Yes, the bundle is still not created, maybe it is a problem at my computer.
To be surely , can show me how to run your app step by step ?
I remind you that I have changed the node ENV as `"build": "SET NODE_ENV=development node foo.js",`

**# UPDATED**: Now, the webpack bundle has create the bundle.js in`src/main/resources/static/app/bundle.js` but there are still many errors, I will list below some of them: 

```
ERROR in ./src/main/js/index.jsx
 1:12  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
 2:62  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
 3:60  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
ERROR in ./src/main/js/containers/App.jsx
    1:12   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
    2:41   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
    3:100  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
    4:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
```

```
✖ 11 problems (11 errors, 0 warnings)
> 
> 
> ERROR in ./~/react-router/~/history/createHashHistory.js
> Module not found: Error: Cannot resolve module 'warning' in D:\Workspace\spring-react-boilerplate\node_modules\react-router\node_modules\history
>  @ ./~/react-router/~/history/createHashHistory.js 7:15-33
> 
> ERROR in ./~/react-router/~/history/createBrowserHistory.js
> Module not found: Error: Cannot resolve module 'warning' in D:\Workspace\spring-react-boilerplate\node_modules\react-router\node_modules\history
>  @ ./~/react-router/~/history/createBrowserHistory.js 9:15-33
> 
> ERROR in ./~/react-router/~/history/createMemoryHistory.js
> Module not found: Error: Cannot resolve module 'warning' in D:\Workspace\spring-react-boilerplate\node_modules\react-router\node_modules\history
>  @ ./~/react-router/~/history/createMemoryHistory.js 9:15-33
> 
> ERROR in ./~/react-router/~/history/createHashHistory.js
> Module not found: Error: Cannot resolve module 'invariant' in D:\Workspace\spring-react-boilerplate\node_modules\react-router\node_modules\history
>  @ ./~/react-router/~/history/createHashHistory.js 11:17-37
> 
> ERROR in ./~/react-router/~/history/createBrowserHistory.js
> Module not found: Error: Cannot resolve module 'invariant' in D:\Workspace\spring-react-boilerplate\node_modules\react-router\node_modules\history
>  @ ./~/react-router/~/history/createBrowserHistory.js 13:17-37
> 
> ERROR in ./~/react-router/~/history/LocationUtils.js
> Module not found: Error: Cannot resolve module 'resolve-pathname' in D:\Workspace\spring-react-boilerplate\node_modules\react-router\node_modules\history
>  @ ./~/react-router/~/history/LocationUtils.js 10:23-50
> 
> ERROR in ./~/react-router/~/history/createTransitionManager.js
> Module not found: Error: Cannot resolve module 'warning' in D:\Workspace\spring-react-boilerplate\node_modules\react-router\node_modules\history
>  @ ./~/react-router/~/history/createTransitionManager.js 5:15-33
> 
```

**Comment by pugnascotia** [comment]
What version of npm are you using? The errors look similar to https://github.com/FormidableLabs/spectacle-boilerplate/issues/6 where using npm v3 worked but v2 didn't.

**Comment by datanguyen** [comment]
Hi Rory,
I can fix all the issue by myself now. Would you like give me a hand to close this issue ?
Anyways, thank you very much for you help :))

**Comment by pugnascotia** [comment]
Ah, great, what did you do to fix your problem?

**Comment by pugnascotia** [comment]
Going to close this issue now, but please do create a pull request if you have changes that would be useful for others.
